### ISSUE TITLE
not open source?

### ISSUE THREAD

**Issue by K1xzy** [MarsQQ/Aimmy#10]
https://github.com/MarsQQ/Aimmy/releases/tag/v1.0.0

source is completely different from Aimmy1_0_0.zip, so where exactly is the source?

**Comment by MarsQQ** [comment]
Hey!

At the time of Aimmy’s release, we kind of screwed up and uploaded the wrong version of Aimmy’s source code (Aimmy .NET Framework 4.7.2) when the release was built off of .NET 7.0.

I have corrected that issue a day ago and now when you pull Aimmy off Github, it will download AimmyWPF, which is the source used to build [the release version](https://github.com/MarsQQ/Aimmy/releases/tag/v1.0.0).

The reason the source now is not exactly the same as the release version is because I’m making some UI tweaks to it. I’m not ready 😅 so it’s not been pushed as a new version, please bare with us =))

License wis, Aimmy does not follow open-source convention (because we actively don’t want our source code to be monetized, that breaks rule 6? of [the open source initiative’s rules.](https://opensource.org/osd/) and is therefore considered source-available, **not** open source.

If you have any questions, you’re free to ask =)

- Nori

**Comment by Babyhamsta** [comment]
Source has been fully updated to the newest version and should be up to date now.
